version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          BUNDLE_PATH: "vendor/bundle"
          BUNDLER_VERSION: 1.16.1
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: '20186hinsitu@'
          MYSQL_DATABASE: app_name_test
          MYSQL_PORT: 3306
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
          
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dependencies-{{ checksum "app/views/devise/sessions/new.html.haml" }}
            - m2-dependencies- 
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies- 
      - run:
          name: yarn install --check-files
          command: |
            yarn install --check-files
      - run:
          name: install bundle
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      - save_cache:
          paths:
            - ./app/views/devise/sessions
          key: v2-dependencies-{{ checksum "new.html.haml" }}
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      #- run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create
      
      - run:
          name: データベースのセットアップ
          command: bundle exec rake db:schema:load
      - run:
          name: gem install bundler
          command: gem install bundler
            # Align chrome-driver's version installed by chromedriver-helper
      - run: 
          name: rspecを実行
          command: bundle exec rspec
      - store_artifacts:
          path: tmp/screenshots/
          destination: capybara
  
  code-check:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: システムアップデート
          command: |
            sudo gem update --system
      - run:
          name: bundle install
          command: bundle install
      - run: 
          name: rubocopを実行
          command: bundle exec rubocop

workflows:
  version: 2
  workflows:
    jobs:
      - test
      - code-check
